$alTestSuite = 'MEDT01FOO'
$objFilter = 'KVS*'
$devSuite = 'kvsenavdev543'
$tenant = 'kpa'
$company = 'CRONUS AG'
$user = 'kpa'
$pass = 'Start2020'
$cred = [System.Management.Automation.PSCredential]::new($user,(ConvertTo-SecureString $pass -AsPlainText -Force))

# Lädt Object/Test Mappings hoch. Alternativer Weg zu 1_Invoke-BuildObjectTestMapping_ODATA_Codeunit_Unbound_Action

$content = @'
{
    "TestSuite": "MEDT_02FOO",
    "ObjectTestMappings": [{
        "ObjectType": 1,
        "ObjectId": 71076603,
        "ObjectName": "KVSMTCBaseDataAddFieldValue",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5048753,
        "ObjectName": "KVSKBAItemSubscribers",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5048766,
        "ObjectName": "KVSKBAContactLib",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5048783,
        "ObjectName": "KVSKBAMandatoryFieldsLib",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5048795,
        "ObjectName": "KVSKBAAdvertisingGroupMember",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5048820,
        "ObjectName": "KVSKBASyncDepFldContact",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5048880,
        "ObjectName": "KVSKBAPurchaseSubscribers",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5049170,
        "ObjectName": "KVSKBAPriceCalcLowestPrice",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5049171,
        "ObjectName": "KVSKBAPriceHelper",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5049172,
        "ObjectName": "KVSKBAPriceListMgtHelper",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5049179,
        "ObjectName": "KVSKBAPriceListLine",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5049190,
        "ObjectName": "KVSKBAPriceCalcPricePrio",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5049611,
        "ObjectName": "KVSKBAKPBTestRunnerSubscriber",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5049626,
        "ObjectName": "KVSKBAKPBLibrary",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5049627,
        "ObjectName": "KVSKBAKPBIndGeneralSetup",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5049628,
        "ObjectName": "KVSKBAKPBSIBufMgt4TestsKBATests",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5049632,
        "ObjectName": "KVSKBAKPBCopyPurchaseDocuments",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5049662,
        "ObjectName": "KVSKBAKPBLibrarySubscriber",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5487271,
        "ObjectName": "KVSKBAItemLib2",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5487274,
        "ObjectName": "KVSKBAModuleMgt",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5487276,
        "ObjectName": "KVSKBAApplicationAreaMgt",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5487624,
        "ObjectName": "KVSKBAUDIChangeLogManagement",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5488179,
        "ObjectName": "KVSKBACLLCMPComplianceEventMgt",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 5488180,
        "ObjectName": "KVSKBACLLCMPComplianceLib",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 71076581,
        "ObjectName": "KVSMTCAdditionalFieldLib",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 71076643,
        "ObjectName": "KVSMTCContactLib",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 71076706,
        "ObjectName": "KVSMTCGeneralLibMED",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 71076745,
        "ObjectName": "KVSMTCItemLib",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 71076752,
        "ObjectName": "KVSMTCItemSub",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 71076780,
        "ObjectName": "KVSMTCMandatoryFieldsLibTrade",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 71076781,
        "ObjectName": "KVSMTCMandFldsLibCodeunitSub",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 71076909,
        "ObjectName": "KVSMTCUDIChangeLogManSub",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 71076961,
        "ObjectName": "KVSMTCTabContactSub",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 71077007,
        "ObjectName": "KVSMTCUserSetupSub",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 71077008,
        "ObjectName": "KVSMTCVendorSub",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 71077057,
        "ObjectName": "KVSMTCCLLComplianceEventMgmt",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 71077565,
        "ObjectName": "KVSMTCKPBKBASIBufMgt4Tests",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 5,
        "ObjectId": 71077567,
        "ObjectName": "KVSMTCKPBKBATestSubscriber",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 15,
        "ObjectId": 5049170,
        "ObjectName": "KVSKBAPriceListLine",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 15,
        "ObjectId": 71076587,
        "ObjectName": "KVSMTCContact",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 15,
        "ObjectId": 71076628,
        "ObjectName": "KVSMTCItemUnitOfMeasure",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 15,
        "ObjectId": 71076728,
        "ObjectName": "KVSMTCUserSetup",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }, {
        "ObjectType": 15,
        "ObjectId": 71076732,
        "ObjectName": "KVSMTCVendor",
        "TestCodeunitId": 5049632,
        "TestName": "1_1_CreatePurchaseOrderAndArchiveOrder_CreatePurchaseQuoteAndCopyArchivedOrderWithRecalculate_CheckQuoteLines"
      }
    ]
  }
  
'@


$uri =  "https://$tenant.$devSuite.dev.intra:7048/BC/ODataV4/TestSuggestionWebservice_CreateObjectTextMapping/?tenant=$tenant.$devSuite.dev.intra&company=$company"
$body = @{    
    objectTestMappingJson = $content
} | ConvertTo-Json

Write-Host "Requesting unbound action`r`n$uri `r`n`r`napplication/json`r`n$body"
Invoke-RestMethod -Uri $uri -Body $body -Credential $cred -Method Post -ContentType 'application/json'